name: Hourly Echo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/1 * * *"

jobs:
  post-tweet:
    if: github.repository == '9bitofcode/hourly-echo'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install apt dependencies
        run: |
          sudo apt install ffmpeg

      - name: Cache PIP packages
        id: cache-pip-packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: pip-packages-${{ hashFiles('requirements.txt') }}

      - name: Install PIP packages
        if: steps.cache-pip-packages.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Post Tweet
        run: |
          source .venv/bin/activate
          jupyter nbconvert --to python hourly_echo_tweet.ipynb
          ipython hourly_echo_tweet.py -1 ${{ secrets.TWITTER_CONSUMER_KEY }} -2 ${{ secrets.TWITTER_CONSUMER_SECRET }} -3 ${{ secrets.TWITTER_ACCESS_TOKEN }} -4 ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
